# Generated by Django 5.1.4 on 2024-12-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing', models.CharField(max_length=255, verbose_name='Inglizcha')),
                ('uzb', models.CharField(max_length=255, verbose_name="O'zbekcha")),
            ],
            options={
                'verbose_name': "Lug't",
                'verbose_name_plural': "Lug'atlar",
            },
        ),
    ]
